### ISSUE TITLE
build error: $ go build api.go:4:2: no Go files in /usr/local/go/src/database

### ISSUE THREAD

**Issue by fish2016** [McMenemy/GoDoRP#4]
build success in docker environment, but build failed outside docker.
the following is the steps build api outside docker:
```
DJdeMacBook-Pro:api dj$ go get ./vendor/database
go install: no install location for directory /Users/dj/WorkSpace/GitSpace/10_19/goDR_12_16/GoDoRP/api/vendor/database outside GOPATH
	For more details see: 'go help gopath'
DJdeMacBook-Pro:api dj$ go get .
api.go:4:2: no Go files in /usr/local/go/src/database
DJdeMacBook-Pro:api dj$ go build
api.go:4:2: no Go files in /usr/local/go/src/database
DJdeMacBook-Pro:api dj$ go version
go version go1.9.2 darwin/amd64
DJdeMacBook-Pro:api dj$ 
```
```
`DJdeMacBook-Pro:api dj$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/dj/WorkSpace/GitSpace/10_19/goDR_12_16/GoDoRP"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dz/n0nt7d3924g6h5436gfc6xsc0000gn/T/go-build606782250=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
DJdeMacBook-Pro:api dj$ `
```

golang version is 1.9.2;

I guess this error is related with vendor fearture, but I don't know how to fix.

can you help me for this issue?

**Comment by McMenemy** [comment]
Hi @fish2016. I have not contributed to this repo in a while, but it looks like your [go path](https://golang.org/doc/code.html#GOPATH) is not set up correctly. Have you successfully started up other golang projects?

Also, one the features of this project is that you could develop without needing to set up go.

Lastly, go is now working on an [official package manager tool ](https://github.com/golang/dep), so I would now use that instead of a vendor folder.

**Comment by fish2016** [comment]
after create a  folder "src" and move "api" into "src",  this error is fixed, 

the cause is the file struct of go,  I need build this project outside docker
